//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.269
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.269。
// 
#pragma warning disable 1591

namespace WinFormLogin.Portal {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SIM_ServicePortBinding", Namespace="http://services.ldap.tku.edu.tw/")]
    public partial class SIM_ServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback authenticationOperationCompleted;
        
        private System.Threading.SendOrPostCallback isMemberOfOperationCompleted;
        
        private System.Threading.SendOrPostCallback isMemberOfByUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMemberOfGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMemberOfGroupByUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback getGroupListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getGroupListByUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback getGroupListByDeptOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SIM_ServiceService() {
            this.Url = global::WinFormLogin.Properties.Settings.Default.WinFormLogin_Portal_SIM_ServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event authenticationCompletedEventHandler authenticationCompleted;
        
        /// <remarks/>
        public event isMemberOfCompletedEventHandler isMemberOfCompleted;
        
        /// <remarks/>
        public event isMemberOfByUserCompletedEventHandler isMemberOfByUserCompleted;
        
        /// <remarks/>
        public event getMemberOfGroupCompletedEventHandler getMemberOfGroupCompleted;
        
        /// <remarks/>
        public event getMemberOfGroupByUserCompletedEventHandler getMemberOfGroupByUserCompleted;
        
        /// <remarks/>
        public event getGroupListCompletedEventHandler getGroupListCompleted;
        
        /// <remarks/>
        public event getGroupListByUserCompletedEventHandler getGroupListByUserCompleted;
        
        /// <remarks/>
        public event getGroupListByDeptCompletedEventHandler getGroupListByDeptCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://services.ldap.tku.edu.tw/", ResponseNamespace="http://services.ldap.tku.edu.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tkUperson authentication([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg3) {
            object[] results = this.Invoke("authentication", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3});
            return ((tkUperson)(results[0]));
        }
        
        /// <remarks/>
        public void authenticationAsync(string arg0, string arg1, string arg2, string arg3) {
            this.authenticationAsync(arg0, arg1, arg2, arg3, null);
        }
        
        /// <remarks/>
        public void authenticationAsync(string arg0, string arg1, string arg2, string arg3, object userState) {
            if ((this.authenticationOperationCompleted == null)) {
                this.authenticationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthenticationOperationCompleted);
            }
            this.InvokeAsync("authentication", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3}, this.authenticationOperationCompleted, userState);
        }
        
        private void OnauthenticationOperationCompleted(object arg) {
            if ((this.authenticationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.authenticationCompleted(this, new authenticationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://services.ldap.tku.edu.tw/", ResponseNamespace="http://services.ldap.tku.edu.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int isMemberOf([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg3) {
            object[] results = this.Invoke("isMemberOf", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void isMemberOfAsync(string arg0, string arg1, string arg2, string arg3) {
            this.isMemberOfAsync(arg0, arg1, arg2, arg3, null);
        }
        
        /// <remarks/>
        public void isMemberOfAsync(string arg0, string arg1, string arg2, string arg3, object userState) {
            if ((this.isMemberOfOperationCompleted == null)) {
                this.isMemberOfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisMemberOfOperationCompleted);
            }
            this.InvokeAsync("isMemberOf", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3}, this.isMemberOfOperationCompleted, userState);
        }
        
        private void OnisMemberOfOperationCompleted(object arg) {
            if ((this.isMemberOfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isMemberOfCompleted(this, new isMemberOfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://services.ldap.tku.edu.tw/", ResponseNamespace="http://services.ldap.tku.edu.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int isMemberOfByUser([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg3, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg4) {
            object[] results = this.Invoke("isMemberOfByUser", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void isMemberOfByUserAsync(string arg0, string arg1, string arg2, string arg3, string arg4) {
            this.isMemberOfByUserAsync(arg0, arg1, arg2, arg3, arg4, null);
        }
        
        /// <remarks/>
        public void isMemberOfByUserAsync(string arg0, string arg1, string arg2, string arg3, string arg4, object userState) {
            if ((this.isMemberOfByUserOperationCompleted == null)) {
                this.isMemberOfByUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisMemberOfByUserOperationCompleted);
            }
            this.InvokeAsync("isMemberOfByUser", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4}, this.isMemberOfByUserOperationCompleted, userState);
        }
        
        private void OnisMemberOfByUserOperationCompleted(object arg) {
            if ((this.isMemberOfByUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isMemberOfByUserCompleted(this, new isMemberOfByUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://services.ldap.tku.edu.tw/", ResponseNamespace="http://services.ldap.tku.edu.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public tkUperson[] getMemberOfGroup([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2) {
            object[] results = this.Invoke("getMemberOfGroup", new object[] {
                        arg0,
                        arg1,
                        arg2});
            return ((tkUperson[])(results[0]));
        }
        
        /// <remarks/>
        public void getMemberOfGroupAsync(string arg0, string arg1, string arg2) {
            this.getMemberOfGroupAsync(arg0, arg1, arg2, null);
        }
        
        /// <remarks/>
        public void getMemberOfGroupAsync(string arg0, string arg1, string arg2, object userState) {
            if ((this.getMemberOfGroupOperationCompleted == null)) {
                this.getMemberOfGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMemberOfGroupOperationCompleted);
            }
            this.InvokeAsync("getMemberOfGroup", new object[] {
                        arg0,
                        arg1,
                        arg2}, this.getMemberOfGroupOperationCompleted, userState);
        }
        
        private void OngetMemberOfGroupOperationCompleted(object arg) {
            if ((this.getMemberOfGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMemberOfGroupCompleted(this, new getMemberOfGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://services.ldap.tku.edu.tw/", ResponseNamespace="http://services.ldap.tku.edu.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public tkUperson[] getMemberOfGroupByUser([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg3) {
            object[] results = this.Invoke("getMemberOfGroupByUser", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3});
            return ((tkUperson[])(results[0]));
        }
        
        /// <remarks/>
        public void getMemberOfGroupByUserAsync(string arg0, string arg1, string arg2, string arg3) {
            this.getMemberOfGroupByUserAsync(arg0, arg1, arg2, arg3, null);
        }
        
        /// <remarks/>
        public void getMemberOfGroupByUserAsync(string arg0, string arg1, string arg2, string arg3, object userState) {
            if ((this.getMemberOfGroupByUserOperationCompleted == null)) {
                this.getMemberOfGroupByUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMemberOfGroupByUserOperationCompleted);
            }
            this.InvokeAsync("getMemberOfGroupByUser", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3}, this.getMemberOfGroupByUserOperationCompleted, userState);
        }
        
        private void OngetMemberOfGroupByUserOperationCompleted(object arg) {
            if ((this.getMemberOfGroupByUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMemberOfGroupByUserCompleted(this, new getMemberOfGroupByUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://services.ldap.tku.edu.tw/", ResponseNamespace="http://services.ldap.tku.edu.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public tkuGroup[] getGroupList([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2) {
            object[] results = this.Invoke("getGroupList", new object[] {
                        arg0,
                        arg1,
                        arg2});
            return ((tkuGroup[])(results[0]));
        }
        
        /// <remarks/>
        public void getGroupListAsync(int arg0, string arg1, string arg2) {
            this.getGroupListAsync(arg0, arg1, arg2, null);
        }
        
        /// <remarks/>
        public void getGroupListAsync(int arg0, string arg1, string arg2, object userState) {
            if ((this.getGroupListOperationCompleted == null)) {
                this.getGroupListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetGroupListOperationCompleted);
            }
            this.InvokeAsync("getGroupList", new object[] {
                        arg0,
                        arg1,
                        arg2}, this.getGroupListOperationCompleted, userState);
        }
        
        private void OngetGroupListOperationCompleted(object arg) {
            if ((this.getGroupListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getGroupListCompleted(this, new getGroupListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://services.ldap.tku.edu.tw/", ResponseNamespace="http://services.ldap.tku.edu.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public tkuGroup[] getGroupListByUser([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2) {
            object[] results = this.Invoke("getGroupListByUser", new object[] {
                        arg0,
                        arg1,
                        arg2});
            return ((tkuGroup[])(results[0]));
        }
        
        /// <remarks/>
        public void getGroupListByUserAsync(string arg0, string arg1, string arg2) {
            this.getGroupListByUserAsync(arg0, arg1, arg2, null);
        }
        
        /// <remarks/>
        public void getGroupListByUserAsync(string arg0, string arg1, string arg2, object userState) {
            if ((this.getGroupListByUserOperationCompleted == null)) {
                this.getGroupListByUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetGroupListByUserOperationCompleted);
            }
            this.InvokeAsync("getGroupListByUser", new object[] {
                        arg0,
                        arg1,
                        arg2}, this.getGroupListByUserOperationCompleted, userState);
        }
        
        private void OngetGroupListByUserOperationCompleted(object arg) {
            if ((this.getGroupListByUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getGroupListByUserCompleted(this, new getGroupListByUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://services.ldap.tku.edu.tw/", ResponseNamespace="http://services.ldap.tku.edu.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public tkuGroup[] getGroupListByDept([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2) {
            object[] results = this.Invoke("getGroupListByDept", new object[] {
                        arg0,
                        arg1,
                        arg2});
            return ((tkuGroup[])(results[0]));
        }
        
        /// <remarks/>
        public void getGroupListByDeptAsync(string arg0, string arg1, string arg2) {
            this.getGroupListByDeptAsync(arg0, arg1, arg2, null);
        }
        
        /// <remarks/>
        public void getGroupListByDeptAsync(string arg0, string arg1, string arg2, object userState) {
            if ((this.getGroupListByDeptOperationCompleted == null)) {
                this.getGroupListByDeptOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetGroupListByDeptOperationCompleted);
            }
            this.InvokeAsync("getGroupListByDept", new object[] {
                        arg0,
                        arg1,
                        arg2}, this.getGroupListByDeptOperationCompleted, userState);
        }
        
        private void OngetGroupListByDeptOperationCompleted(object arg) {
            if ((this.getGroupListByDeptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getGroupListByDeptCompleted(this, new getGroupListByDeptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ldap.tku.edu.tw/")]
    public partial class tkUperson {
        
        private string ab_coll_clsField;
        
        private string birth_dateField;
        
        private string ch_coll_nameField;
        
        private string ch_dept_nameField;
        
        private string ch_nameField;
        
        private string clsField;
        
        private string clsf_cdField;
        
        private string clsf_cd_1Field;
        
        private string clsf_cd_2Field;
        
        private string clsf_cd_3Field;
        
        private string clsf_cd_4Field;
        
        private string clsf_cd_5Field;
        
        private string clsf_nameField;
        
        private string clsf_name_1Field;
        
        private string clsf_name_2Field;
        
        private string clsf_name_3Field;
        
        private string clsf_name_4Field;
        
        private string clsf_name_5Field;
        
        private string collField;
        
        private string coll_sectField;
        
        private string dept_cdField;
        
        private string dept_cd_1Field;
        
        private string dept_cd_2Field;
        
        private string dept_cd_3Field;
        
        private string dept_cd_4Field;
        
        private string dept_cd_5Field;
        
        private string dept_nameField;
        
        private string dept_name_1Field;
        
        private string dept_name_2Field;
        
        private string dept_name_3Field;
        
        private string dept_name_4Field;
        
        private string dept_name_5Field;
        
        private string duty_typeField;
        
        private string duty_type_1Field;
        
        private string duty_type_2Field;
        
        private string duty_type_3Field;
        
        private string duty_type_4Field;
        
        private string duty_type_5Field;
        
        private string duty_type_nameField;
        
        private string duty_type_name_1Field;
        
        private string duty_type_name_2Field;
        
        private string duty_type_name_3Field;
        
        private string duty_type_name_4Field;
        
        private string duty_type_name_5Field;
        
        private string edu_cdField;
        
        private string edu_grp_nameField;
        
        private string emp_emailField;
        
        private string empl_noField;
        
        private string en_nameField;
        
        private string ext_emp_emailField;
        
        private string ext_stu_emailField;
        
        private string ftpt_typeField;
        
        private string ftpt_type_1Field;
        
        private string ftpt_type_2Field;
        
        private string ftpt_type_3Field;
        
        private string ftpt_type_4Field;
        
        private string ftpt_type_5Field;
        
        private string ftpt_type_nameField;
        
        private string ftpt_type_name_1Field;
        
        private string ftpt_type_name_2Field;
        
        private string ftpt_type_name_3Field;
        
        private string ftpt_type_name_4Field;
        
        private string ftpt_type_name_5Field;
        
        private string gradeField;
        
        private string id_noField;
        
        private string new_dateField;
        
        private string now_staField;
        
        private string pswdField;
        
        private string quit_dateField;
        
        private string reg_cdField;
        
        private string semField;
        
        private string sexField;
        
        private string status1Field;
        
        private string status2Field;
        
        private string status3Field;
        
        private string status4Field;
        
        private string stu_emailField;
        
        private string stu_noField;
        
        private string stu_reg_typeField;
        
        private string study_staField;
        
        private string telField;
        
        private string tel_noField;
        
        private string title_cdField;
        
        private string title_cd_1Field;
        
        private string title_cd_2Field;
        
        private string title_cd_3Field;
        
        private string title_cd_4Field;
        
        private string title_cd_5Field;
        
        private string title_nameField;
        
        private string title_name_1Field;
        
        private string title_name_2Field;
        
        private string title_name_3Field;
        
        private string title_name_4Field;
        
        private string title_name_5Field;
        
        private string typeField;
        
        private string type_1Field;
        
        private string type_2Field;
        
        private string type_3Field;
        
        private string type_4Field;
        
        private string type_5Field;
        
        private string type_nameField;
        
        private string type_name_1Field;
        
        private string type_name_2Field;
        
        private string type_name_3Field;
        
        private string type_name_4Field;
        
        private string type_name_5Field;
        
        private string uidField;
        
        private string unit1Field;
        
        private string unit1_1Field;
        
        private string unit1_2Field;
        
        private string unit1_3Field;
        
        private string unit1_4Field;
        
        private string unit1_5Field;
        
        private string unit1_nameField;
        
        private string unit1_name_1Field;
        
        private string unit1_name_2Field;
        
        private string unit1_name_3Field;
        
        private string unit1_name_4Field;
        
        private string unit1_name_5Field;
        
        private string user_typeField;
        
        private string yrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ab_coll_cls {
            get {
                return this.ab_coll_clsField;
            }
            set {
                this.ab_coll_clsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string birth_date {
            get {
                return this.birth_dateField;
            }
            set {
                this.birth_dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ch_coll_name {
            get {
                return this.ch_coll_nameField;
            }
            set {
                this.ch_coll_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ch_dept_name {
            get {
                return this.ch_dept_nameField;
            }
            set {
                this.ch_dept_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ch_name {
            get {
                return this.ch_nameField;
            }
            set {
                this.ch_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cls {
            get {
                return this.clsField;
            }
            set {
                this.clsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clsf_cd {
            get {
                return this.clsf_cdField;
            }
            set {
                this.clsf_cdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clsf_cd_1 {
            get {
                return this.clsf_cd_1Field;
            }
            set {
                this.clsf_cd_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clsf_cd_2 {
            get {
                return this.clsf_cd_2Field;
            }
            set {
                this.clsf_cd_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clsf_cd_3 {
            get {
                return this.clsf_cd_3Field;
            }
            set {
                this.clsf_cd_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clsf_cd_4 {
            get {
                return this.clsf_cd_4Field;
            }
            set {
                this.clsf_cd_4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clsf_cd_5 {
            get {
                return this.clsf_cd_5Field;
            }
            set {
                this.clsf_cd_5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clsf_name {
            get {
                return this.clsf_nameField;
            }
            set {
                this.clsf_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clsf_name_1 {
            get {
                return this.clsf_name_1Field;
            }
            set {
                this.clsf_name_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clsf_name_2 {
            get {
                return this.clsf_name_2Field;
            }
            set {
                this.clsf_name_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clsf_name_3 {
            get {
                return this.clsf_name_3Field;
            }
            set {
                this.clsf_name_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clsf_name_4 {
            get {
                return this.clsf_name_4Field;
            }
            set {
                this.clsf_name_4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clsf_name_5 {
            get {
                return this.clsf_name_5Field;
            }
            set {
                this.clsf_name_5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string coll {
            get {
                return this.collField;
            }
            set {
                this.collField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string coll_sect {
            get {
                return this.coll_sectField;
            }
            set {
                this.coll_sectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dept_cd {
            get {
                return this.dept_cdField;
            }
            set {
                this.dept_cdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dept_cd_1 {
            get {
                return this.dept_cd_1Field;
            }
            set {
                this.dept_cd_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dept_cd_2 {
            get {
                return this.dept_cd_2Field;
            }
            set {
                this.dept_cd_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dept_cd_3 {
            get {
                return this.dept_cd_3Field;
            }
            set {
                this.dept_cd_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dept_cd_4 {
            get {
                return this.dept_cd_4Field;
            }
            set {
                this.dept_cd_4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dept_cd_5 {
            get {
                return this.dept_cd_5Field;
            }
            set {
                this.dept_cd_5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dept_name {
            get {
                return this.dept_nameField;
            }
            set {
                this.dept_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dept_name_1 {
            get {
                return this.dept_name_1Field;
            }
            set {
                this.dept_name_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dept_name_2 {
            get {
                return this.dept_name_2Field;
            }
            set {
                this.dept_name_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dept_name_3 {
            get {
                return this.dept_name_3Field;
            }
            set {
                this.dept_name_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dept_name_4 {
            get {
                return this.dept_name_4Field;
            }
            set {
                this.dept_name_4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dept_name_5 {
            get {
                return this.dept_name_5Field;
            }
            set {
                this.dept_name_5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string duty_type {
            get {
                return this.duty_typeField;
            }
            set {
                this.duty_typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string duty_type_1 {
            get {
                return this.duty_type_1Field;
            }
            set {
                this.duty_type_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string duty_type_2 {
            get {
                return this.duty_type_2Field;
            }
            set {
                this.duty_type_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string duty_type_3 {
            get {
                return this.duty_type_3Field;
            }
            set {
                this.duty_type_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string duty_type_4 {
            get {
                return this.duty_type_4Field;
            }
            set {
                this.duty_type_4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string duty_type_5 {
            get {
                return this.duty_type_5Field;
            }
            set {
                this.duty_type_5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string duty_type_name {
            get {
                return this.duty_type_nameField;
            }
            set {
                this.duty_type_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string duty_type_name_1 {
            get {
                return this.duty_type_name_1Field;
            }
            set {
                this.duty_type_name_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string duty_type_name_2 {
            get {
                return this.duty_type_name_2Field;
            }
            set {
                this.duty_type_name_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string duty_type_name_3 {
            get {
                return this.duty_type_name_3Field;
            }
            set {
                this.duty_type_name_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string duty_type_name_4 {
            get {
                return this.duty_type_name_4Field;
            }
            set {
                this.duty_type_name_4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string duty_type_name_5 {
            get {
                return this.duty_type_name_5Field;
            }
            set {
                this.duty_type_name_5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string edu_cd {
            get {
                return this.edu_cdField;
            }
            set {
                this.edu_cdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string edu_grp_name {
            get {
                return this.edu_grp_nameField;
            }
            set {
                this.edu_grp_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string emp_email {
            get {
                return this.emp_emailField;
            }
            set {
                this.emp_emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string empl_no {
            get {
                return this.empl_noField;
            }
            set {
                this.empl_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string en_name {
            get {
                return this.en_nameField;
            }
            set {
                this.en_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ext_emp_email {
            get {
                return this.ext_emp_emailField;
            }
            set {
                this.ext_emp_emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ext_stu_email {
            get {
                return this.ext_stu_emailField;
            }
            set {
                this.ext_stu_emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ftpt_type {
            get {
                return this.ftpt_typeField;
            }
            set {
                this.ftpt_typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ftpt_type_1 {
            get {
                return this.ftpt_type_1Field;
            }
            set {
                this.ftpt_type_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ftpt_type_2 {
            get {
                return this.ftpt_type_2Field;
            }
            set {
                this.ftpt_type_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ftpt_type_3 {
            get {
                return this.ftpt_type_3Field;
            }
            set {
                this.ftpt_type_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ftpt_type_4 {
            get {
                return this.ftpt_type_4Field;
            }
            set {
                this.ftpt_type_4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ftpt_type_5 {
            get {
                return this.ftpt_type_5Field;
            }
            set {
                this.ftpt_type_5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ftpt_type_name {
            get {
                return this.ftpt_type_nameField;
            }
            set {
                this.ftpt_type_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ftpt_type_name_1 {
            get {
                return this.ftpt_type_name_1Field;
            }
            set {
                this.ftpt_type_name_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ftpt_type_name_2 {
            get {
                return this.ftpt_type_name_2Field;
            }
            set {
                this.ftpt_type_name_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ftpt_type_name_3 {
            get {
                return this.ftpt_type_name_3Field;
            }
            set {
                this.ftpt_type_name_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ftpt_type_name_4 {
            get {
                return this.ftpt_type_name_4Field;
            }
            set {
                this.ftpt_type_name_4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ftpt_type_name_5 {
            get {
                return this.ftpt_type_name_5Field;
            }
            set {
                this.ftpt_type_name_5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string grade {
            get {
                return this.gradeField;
            }
            set {
                this.gradeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id_no {
            get {
                return this.id_noField;
            }
            set {
                this.id_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string new_date {
            get {
                return this.new_dateField;
            }
            set {
                this.new_dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string now_sta {
            get {
                return this.now_staField;
            }
            set {
                this.now_staField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pswd {
            get {
                return this.pswdField;
            }
            set {
                this.pswdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string quit_date {
            get {
                return this.quit_dateField;
            }
            set {
                this.quit_dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reg_cd {
            get {
                return this.reg_cdField;
            }
            set {
                this.reg_cdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sem {
            get {
                return this.semField;
            }
            set {
                this.semField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string status1 {
            get {
                return this.status1Field;
            }
            set {
                this.status1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string status2 {
            get {
                return this.status2Field;
            }
            set {
                this.status2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string status3 {
            get {
                return this.status3Field;
            }
            set {
                this.status3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string status4 {
            get {
                return this.status4Field;
            }
            set {
                this.status4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stu_email {
            get {
                return this.stu_emailField;
            }
            set {
                this.stu_emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stu_no {
            get {
                return this.stu_noField;
            }
            set {
                this.stu_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stu_reg_type {
            get {
                return this.stu_reg_typeField;
            }
            set {
                this.stu_reg_typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string study_sta {
            get {
                return this.study_staField;
            }
            set {
                this.study_staField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tel {
            get {
                return this.telField;
            }
            set {
                this.telField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tel_no {
            get {
                return this.tel_noField;
            }
            set {
                this.tel_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string title_cd {
            get {
                return this.title_cdField;
            }
            set {
                this.title_cdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string title_cd_1 {
            get {
                return this.title_cd_1Field;
            }
            set {
                this.title_cd_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string title_cd_2 {
            get {
                return this.title_cd_2Field;
            }
            set {
                this.title_cd_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string title_cd_3 {
            get {
                return this.title_cd_3Field;
            }
            set {
                this.title_cd_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string title_cd_4 {
            get {
                return this.title_cd_4Field;
            }
            set {
                this.title_cd_4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string title_cd_5 {
            get {
                return this.title_cd_5Field;
            }
            set {
                this.title_cd_5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string title_name {
            get {
                return this.title_nameField;
            }
            set {
                this.title_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string title_name_1 {
            get {
                return this.title_name_1Field;
            }
            set {
                this.title_name_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string title_name_2 {
            get {
                return this.title_name_2Field;
            }
            set {
                this.title_name_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string title_name_3 {
            get {
                return this.title_name_3Field;
            }
            set {
                this.title_name_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string title_name_4 {
            get {
                return this.title_name_4Field;
            }
            set {
                this.title_name_4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string title_name_5 {
            get {
                return this.title_name_5Field;
            }
            set {
                this.title_name_5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type_1 {
            get {
                return this.type_1Field;
            }
            set {
                this.type_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type_2 {
            get {
                return this.type_2Field;
            }
            set {
                this.type_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type_3 {
            get {
                return this.type_3Field;
            }
            set {
                this.type_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type_4 {
            get {
                return this.type_4Field;
            }
            set {
                this.type_4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type_5 {
            get {
                return this.type_5Field;
            }
            set {
                this.type_5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type_name {
            get {
                return this.type_nameField;
            }
            set {
                this.type_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type_name_1 {
            get {
                return this.type_name_1Field;
            }
            set {
                this.type_name_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type_name_2 {
            get {
                return this.type_name_2Field;
            }
            set {
                this.type_name_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type_name_3 {
            get {
                return this.type_name_3Field;
            }
            set {
                this.type_name_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type_name_4 {
            get {
                return this.type_name_4Field;
            }
            set {
                this.type_name_4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type_name_5 {
            get {
                return this.type_name_5Field;
            }
            set {
                this.type_name_5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unit1 {
            get {
                return this.unit1Field;
            }
            set {
                this.unit1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unit1_1 {
            get {
                return this.unit1_1Field;
            }
            set {
                this.unit1_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unit1_2 {
            get {
                return this.unit1_2Field;
            }
            set {
                this.unit1_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unit1_3 {
            get {
                return this.unit1_3Field;
            }
            set {
                this.unit1_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unit1_4 {
            get {
                return this.unit1_4Field;
            }
            set {
                this.unit1_4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unit1_5 {
            get {
                return this.unit1_5Field;
            }
            set {
                this.unit1_5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unit1_name {
            get {
                return this.unit1_nameField;
            }
            set {
                this.unit1_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unit1_name_1 {
            get {
                return this.unit1_name_1Field;
            }
            set {
                this.unit1_name_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unit1_name_2 {
            get {
                return this.unit1_name_2Field;
            }
            set {
                this.unit1_name_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unit1_name_3 {
            get {
                return this.unit1_name_3Field;
            }
            set {
                this.unit1_name_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unit1_name_4 {
            get {
                return this.unit1_name_4Field;
            }
            set {
                this.unit1_name_4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unit1_name_5 {
            get {
                return this.unit1_name_5Field;
            }
            set {
                this.unit1_name_5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user_type {
            get {
                return this.user_typeField;
            }
            set {
                this.user_typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string yr {
            get {
                return this.yrField;
            }
            set {
                this.yrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ldap.tku.edu.tw/")]
    public partial class tkuGroup {
        
        private string cnameField;
        
        private string enameField;
        
        private string gidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cname {
            get {
                return this.cnameField;
            }
            set {
                this.cnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ename {
            get {
                return this.enameField;
            }
            set {
                this.enameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gid {
            get {
                return this.gidField;
            }
            set {
                this.gidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void authenticationCompletedEventHandler(object sender, authenticationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class authenticationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal authenticationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tkUperson Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tkUperson)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void isMemberOfCompletedEventHandler(object sender, isMemberOfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isMemberOfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isMemberOfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void isMemberOfByUserCompletedEventHandler(object sender, isMemberOfByUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isMemberOfByUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isMemberOfByUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getMemberOfGroupCompletedEventHandler(object sender, getMemberOfGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMemberOfGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMemberOfGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tkUperson[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tkUperson[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getMemberOfGroupByUserCompletedEventHandler(object sender, getMemberOfGroupByUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMemberOfGroupByUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMemberOfGroupByUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tkUperson[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tkUperson[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getGroupListCompletedEventHandler(object sender, getGroupListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getGroupListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getGroupListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tkuGroup[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tkuGroup[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getGroupListByUserCompletedEventHandler(object sender, getGroupListByUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getGroupListByUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getGroupListByUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tkuGroup[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tkuGroup[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getGroupListByDeptCompletedEventHandler(object sender, getGroupListByDeptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getGroupListByDeptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getGroupListByDeptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tkuGroup[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tkuGroup[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591